; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

#[env:nodemcuv2]
[env:nodemcu-32s]
#platform = espressif8266
platform = espressif32
#board = nodemcuv2
board = nodemcu-32s
framework = arduino
upload_speed = 921600
#upload_port = COM11
debug_tool = esp-prog
debug_init_break = tbreak setup
upload_protocol = esp-prog
#monitor_port = COM10

monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++2a


