; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[bqchip]
build_flags = 
    -D BQ20Z9XX
;    -D BQ40Z6XX

[platformio]
default_envs = nodemcuv2           ; for using ESP8266 processor
;default_envs = nodemcu-32s         ; for using ESP32 processor
;default_envs = nucleo_g070rb       ; for using STM32 processor

; Options valid for all configs
[env]
extends = bqchip
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_unflags = -std=gnu++11
debug_init_break = tbreak setup
build_flags = 
    -std=gnu++2a
    ${bqchip.build_flags}
;upload_port = COM6

;esp8266 config:
[env:nodemcuv2]
extends = env
platform = espressif8266
board = nodemcuv2
debug_tool = esp-prog
upload_protocol = esptool
build_flags = 
    ${env.build_flags}  ; Include general build flags
    -D ESP8266 

;ESP32 config:
[env:nodemcu-32s]
extends = env
board = nodemcu-32s
platform = espressif32
debug_tool = esp-prog
upload_protocol = esptool
build_flags = 
    ${env.build_flags}  ; Include general build flags
    -D ESP32

;ST STM32 config:
[env:nucleo_g070rb]
extends = env
platform = ststm32
board = nucleo_g070rb
; change microcontroller
board_build.mcu = stm32g070rbt6
; change MCU frequency
board_build.f_cpu = 64000000L
upload_protocol = stlink
debug_tool = stlink
debug_build_flags = -O0 -ggdb3 -g3
build_flags = 
    ${env.build_flags}  ; Include general build flags
    -D STM32

